on:
  push:
    branches:
      - main
  
run-name: Deploy to dev
name: branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying"