run-name: Deploy to dev - Feature Branch
name: Deploy to dev - Feature Branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  hold_deploy:
    name: Hold Deploy
    environment:
      name: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Hold Deployment
        run: echo "Deployment Hold Released"
  deploy:
    needs: hold_deploy
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Deploy
        uses: ./.github/actions/deploy
