run-name: Deploy to dev - Feature Branch
name: ${{ inputs.branch }}

on:
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:
  hold_deploy:
    name: Hold Deploy
    environment:
      name: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Hold Deployment
        run: echo "Hold for Deployment"
  deploy:
    needs: hold_deploy
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Call deployment here pause"
