on:
  pull_request:
    branches:
      - '!main'
  
run-name: Deploy to dev
name: branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Hold Deployment
        run: echo "Hold for Deployment"